[package]
name = "rustapp"
version = "0.1.0"
authors = ["jack"]
edition = "2018"

[dependencies]
karplus_string = { path = "../wasm/karplus_string" }
crossbeam-channel = "0.4"
gtk = "0.5"
audio_thread_priority = "0.3"
portaudio = "0.7.0"
rand = "0.7.3"

[profile.release]
lto = true