[package]
name = "karplus"
version = "0.1.0"
authors = ["jack"]
edition = "2018"

[dependencies]
karplus_string = { path = "../karplus_string" }

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

